name: CI

on: [pull_request, push]

jobs:
  test-docker:
    strategy:
      fail-fast: false
      matrix:
        include:
          - container: wpilib/ubuntu-base:18.04
            artifact-name: Linux
    name: "Test - ${{ matrix.artifact-name }}"
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    env:
      DISPLAY: ':10'
    steps:
      - uses: actions/checkout@v2
      - name: Install and start xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          Xvfb :10 &
      - name: Check
        run: ./gradlew check -PbuildServer

  test-host:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            artifact-name: Win64
            architecture: x64
          - os: windows-latest
            artifact-name: Win32
            architecture: x86
          - os: macos-latest
            artifact-name: macOS
            architecture: x64
    name: "Test - ${{ matrix.artifact-name }}"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
          architecture: ${{ matrix.architecture }}
      - name: Check
        run: ./gradlew check -PbuildServer

  publish:
    name: Publish
    needs: [test-docker, test-host]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch all history and metadata
        run: git fetch --prune --unshallow
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Publish
        if: |
          !startsWith(github.ref, 'refs/tags/v') &&
          github.ref != 'refs/heads/master'
        run: ./gradlew publish -PbuildServer
      - name: Publish (Master)
        if: |
          github.repository_owner == 'wpilibsuite' &&
          github.ref == 'refs/heads/master'
        run: ./gradlew publish -PbuildServer
        env:
          RUN_AZURE_ARTIFACTORY_RELEASE: 'TRUE'
          ARTIFACTORY_PUBLISH_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PUBLISH_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
      - name: Publish (Release)
        if: |
          github.repository_owner == 'wpilibsuite' &&
          startsWith(github.ref, 'refs/tags/v')
        run: ./gradlew publish -PbuildServer -PreleaseMode
        env:
          RUN_AZURE_ARTIFACTORY_RELEASE: 'TRUE'
          ARTIFACTORY_PUBLISH_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PUBLISH_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
      - uses: actions/upload-artifact@v2
        with:
          name: RobotBuilder
          path: build/libs/RobotBuilder-all.jar
